### ISSUE TITLE
断线重联导致的机器人加入的问题

### ISSUE THREAD

**Issue by WhymustIhaveaname** [Gongzhu-Society/Arena_Client#5]
### 问题复现
启动server，启动FSM，开房间，增加机器人，打牌，一切正常
重启FSM，用新的号登陆（因为老号会登进刚才的房间），开房间，增加机器人，`state error in enter room`
同时还有另一个问题，关闭FSM后，这个FSM对应的机器人仍然会显示在网页上，这时候用户点击当然不会成功

### 备注
* 阿里云上我已经整理干净了，按李超的方法用__init__.py的方法添加机器人。启动阿里云上的FSM就有Random、If 和 Greed 可以用于测试。
* GitHub 上同步了 __init__.py.demo 而不是 __init__.py。因为每个人的本地机器人都不一样，所以便捷的操作是clone之后去掉demo——这样__init__.py就不会被新的pull影响。我日后会写一个README。
* 同步至github时请用`git push origin HEAD:arena_server`而不是简单的`git push`

**Comment by dashu233** [comment]
第一点bug已经修正，短暂关闭FSMclient并重启可以重新连接
关于第二点，这需要进一步讨论。是希望client短暂关闭后用户可以重新连接还是直接取消掉所有robot？如果是前者，那么这些robot不应该消失；如果是后者，这个功能似乎并不必要，因为如果我们提供的client终止运行一定是我们在维护服务器，那此时就不应该有用户在玩。

**Comment by WhymustIhaveaname** [comment]
谢谢李超，李超辛苦了。

第二点的“关闭FSM”不是指有意关闭，而是指网络故障，机器人bug，停电等等导致的下线。我希望这种情况应当把他们从机器人列表中去除。

或者还有一个方法，现在是无论机器人有没有加上，网页都显示成功（甚至我机器人有时候有了bug压根就没有初始化都显示成功），如果能让网页显示失败这第二点也算解决。当然我知道，这需要前端的协助。
